apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:${LOKI_PORT}
    isDefault: true
    uid: loki

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:${PROMETHEUS_PORT}
    uid: prometheus

  - name: Postgres
    type: postgres
    url: ${GF_DATABASE_HOST}:${GF_DATABASE_PORT}
    database: ${GF_DATABASE_NAME}
    user: ${GF_DATABASE_USER}
    secureJsonData:
      password: ${GF_DATABASE_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false
    uid: postgres
